# Generated by Django 5.1.4 on 2024-12-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.TextField(max_length=25)),
                ('telefone', models.TextField(max_length=15)),
                ('tipo', models.CharField(choices=[('admin', 'Administrador'), ('user', 'Usuário')], default='user', max_length=50)),
            ],
        ),
    ]
