# Generated by Django 5.1.4 on 2024-12-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('imagem_url', models.URLField(blank=True, max_length=500, null=True)),
                ('preco', models.FloatField()),
                ('marca', models.TextField()),
                ('tipo', models.TextField()),
            ],
        ),
    ]
