# Generated by Django 5.1.4 on 2024-12-16 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0002_produtos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produtos',
            new_name='Produto',
        ),
    ]
