# Generated by Django 5.1.5 on 2025-01-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0004_carrinho_itemcarrinho_pedido_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='genero',
            field=models.CharField(default='Unisex', max_length=30),
        ),
    ]
