# Generated by Django 5.1.5 on 2025-01-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0005_produto_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='genero',
            field=models.CharField(default='Unissex', max_length=30),
        ),
    ]
