# Generated by Django 5.1.5 on 2025-01-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0008_alter_produto_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='genero',
            field=models.CharField(max_length=30),
        ),
    ]
