# Generated by Django 5.1.5 on 2025-01-27 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0009_alter_produto_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrinho',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_carrinho', to='meu_app.pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='itens',
            field=models.ManyToManyField(blank=True, related_name='pedidos', to='meu_app.itemcarrinho'),
        ),
    ]
