# Generated by Django 5.1.5 on 2025-01-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0010_itemcarrinho_pedido_alter_pedido_itens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='itens',
        ),
        migrations.AddField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(to='meu_app.produto'),
        ),
    ]
