# Generated by Django 5.1.5 on 2025-01-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0011_remove_itemcarrinho_pedido_remove_pedido_itens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='produtos',
        ),
        migrations.AddField(
            model_name='pedido',
            name='itens',
            field=models.ManyToManyField(to='meu_app.itemcarrinho'),
        ),
    ]
