# Generated by Django 5.1.5 on 2025-01-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_app', '0012_remove_pedido_produtos_pedido_itens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='data_pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='itens',
        ),
        migrations.AddField(
            model_name='pedido',
            name='produtos',
            field=models.ManyToManyField(related_name='pedidos', to='meu_app.itemcarrinho'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
